project:
  type: book
  render:
  - index.qmd
  - STATS_COMP_ASSIGN_2.qmd
  output-dir: _site/
book:
  title: Statistical Computing Assignment 2 MSWXIV001
  sidebar:
    border: true
    background: light
    position: right
  navbar:
    search: true
    background: light
  chapters:
  - index.qmd
  - STATS_COMP_ASSIGN_2.qmd
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left
    

